[project]
name = "good-programming-practices"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "numpy",
    "opencv-python",
    "pillow",
    "tqdm",
    "fastapi",
    "pydantic",
    "uvicorn",
    "sqlalchemy",
    "torch",
    "torchvision",
    "ultralytics",
    "transformers",
    "sentencepiece",
    "accelerate",
    "scipy",
    "requests",
    "pyyaml",
    "aio_pika",
]
